version: "3"

volumes:
  db_vol:
  redis_vol:
  media_vol:
  static_vol:

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
  redis_network: 
    driver: bridge

services:
  redis:
    image: redis:latest
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis_network
    volumes:
      - redis_vol:/data
      - ./compose/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres
    #env_file:  
      #- ./django_warehouse/.env
    networks:  
      - db_network
    volumes:
      - db_vol:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword

  web:
    build: ./django_warehouse
    expose:
      - "8000"
    volumes:
      - ./django_warehouse:/var/www/html/django_warehouse
      - static_vol:/var/www/html/django_warehouse/static
      - media_vol:/var/www/html/django_warehouse/media
      - ./compose/uwsgi:/tmp
    networks:
      - nginx_network
      - db_network  
      - redis_network 
    depends_on:
      - db
      - redis
    restart: always
    tty: true
    stdin_open: true

  nginx:
    #build: ./compose/nginx
    image: nginx
    ports:
      #- "80:80"
      - "5050:5050"
      - "443:443"
    expose:
      - "5050"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./compose/nginx/ssl:/usr/share/nginx/ssl
      - ./compose/nginx/log:/var/log/nginx
      - static_vol:/usr/share/nginx/html/static
      - media_vol:/usr/share/nginx/html/media
    networks:
      - nginx_network
    depends_on:
      - web
    restart: always
