# Generated by Django 4.1 on 2023-11-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalspace",
            name="space_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
