# Generated by Django 4.1 on 2023-12-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_customerprofile_delete_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="location",
            new_name="location_name",
        ),
        migrations.AddField(
            model_name="location",
            name="location_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
