# Generated by Django 4.1 on 2023-12-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0005_rename_location_location_location_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "space_type_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("space_type_name", models.CharField(max_length=255)),
                ("dimensions_L", models.CharField(max_length=100, null=True)),
                ("dimensions_W", models.CharField(max_length=100, null=True)),
                ("dimensions_H", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_type_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("unit_type_name", models.CharField(max_length=255)),
                ("dimensions_L", models.CharField(max_length=100, null=True)),
                ("dimensions_W", models.CharField(max_length=100, null=True)),
                ("dimensions_H", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="rental_spaces",
        ),
        migrations.RemoveField(
            model_name="rentalspace",
            name="dimensions",
        ),
        migrations.AddField(
            model_name="item",
            name="item_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalspace",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_spaces",
                to="warehouse.order",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rentalspace",
            name="space_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="rentalspace",
            name="space_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spacetype",
                to="warehouse.spacetype",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unittype",
                to="warehouse.unittype",
            ),
        ),
    ]
