# Generated by Django 4.1 on 2023-12-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0014_remove_rentalspace_price_spacetype_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershiporder",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="membershiporder",
            name="Payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
