# Generated by Django 4.1 on 2023-12-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0019_alter_rentalspace_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerprofile",
            options={"verbose_name": "客戶資料", "verbose_name_plural": "客戶資料"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "儲藏品", "verbose_name_plural": "儲藏品"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "管理倉庫地點", "verbose_name_plural": "管理倉庫地點"},
        ),
        migrations.AlterModelOptions(
            name="membershiporder",
            options={"verbose_name": "購買會員資格訂單", "verbose_name_plural": "購買會員資格訂單"},
        ),
        migrations.AlterModelOptions(
            name="membershiptype",
            options={"verbose_name": "管理會員資格類型", "verbose_name_plural": "管理會員資格類型"},
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={"verbose_name": "夠買商品訂單", "verbose_name_plural": "購買商品訂單"},
        ),
        migrations.AlterModelOptions(
            name="spacetype",
            options={"verbose_name": "管理租賃空間類型", "verbose_name_plural": "管理租賃空間類型"},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"verbose_name": "已存入的儲存箱或單位", "verbose_name_plural": "已存入的儲存箱或單位"},
        ),
        migrations.AlterModelOptions(
            name="unittype",
            options={"verbose_name": "管理儲存單位類型", "verbose_name_plural": "管理儲存單位類型"},
        ),
        migrations.AlterModelOptions(
            name="userbalance",
            options={"verbose_name": "客戶餘額", "verbose_name_plural": "客戶餘額"},
        ),
    ]
