# Generated by Django 5.0 on 2024-01-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_show', '0002_alter_frontendcontent_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontendcontent',
            old_name='value',
            new_name='value1',
        ),
        migrations.AddField(
            model_name='frontendcontent',
            name='value2',
            field=models.TextField(blank=True, null=True, verbose_name='Content2'),
        ),
        migrations.AddField(
            model_name='frontendcontent',
            name='value3',
            field=models.TextField(blank=True, null=True, verbose_name='Content3'),
        ),
    ]
