# Generated by Django 5.0 on 2024-01-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_show', '0003_rename_value_frontendcontent_value1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendcontent',
            name='value1',
            field=models.TextField(verbose_name='Content1'),
        ),
    ]
