# Generated by Django 4.1 on 2023-12-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0006_spacetype_unittype_remove_order_rental_spaces_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalspace",
            name="space_id",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
