# Generated by Django 4.1 on 2023-12-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0008_membershiptype_location_available_space_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
