# Generated by Django 4.1 on 2023-12-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0009_alter_location_location_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="memembershiporder",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="warehouse.location",
            ),
        ),
    ]
