# Generated by Django 4.1 on 2023-12-02 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warehouse", "0010_memembershiporder_location"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MemembershipOrder",
            new_name="MembershipOrder",
        ),
    ]
