# Generated by Django 4.1 on 2023-12-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0011_rename_memembershiporder_membershiporder"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiporder",
            name="membership_type",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.membershiptype",
            ),
        ),
    ]
