# Generated by Django 4.1 on 2023-12-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0012_membershiporder_membership_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershiporder",
            name="end_date",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="membershiporder",
            name="start_date",
            field=models.DateTimeField(blank=True),
        ),
    ]
