# Generated by Django 4.1 on 2023-12-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0013_alter_membershiporder_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalspace",
            name="price",
        ),
        migrations.AddField(
            model_name="spacetype",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
