# Generated by Django 4.1 on 2023-12-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0018_alter_item_item_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rentalspace",
            options={"verbose_name": "已租賃空間", "verbose_name_plural": "已租賃空間"},
        ),
    ]
