# Generated by Django 5.0 on 2024-01-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontendcontent',
            options={'verbose_name': '管理顯示文字內容', 'verbose_name_plural': '管理顯示文字內容'},
        ),
        migrations.AlterModelOptions(
            name='frontendimage',
            options={'verbose_name': '管理顯示圖片', 'verbose_name_plural': '管理顯示圖片'},
        ),
    ]
